import {
  day,
  demoActivities,
  demoBrands,
  demoCompanies,
  demoCreatorLedger,
  demoExpenses,
  demoInfluencers,
  demoInvoices,
  demoLeads,
  demoOperationsQueue,
  demoQuotations,
} from "./demo-seed";
import type { CompaniesState, Currency } from "./types";

export const branchCurrencies: Record<string, Currency> = {
  Bahrain: "BHD",
  Egypt: "EGP",
  Kuwait: "KWD",
  Qatar: "QAR",
  "Saudi Arabia": "SAR",
  UAE: "AED",
};

export const initialCompaniesState: CompaniesState = {
  creatorLedger: demoCreatorLedger,
  expenses: demoExpenses,
  leads: demoLeads,
  companies: demoCompanies,
  brands: demoBrands,
  campaigns: demoQuotations,
  activities: demoActivities,
  attachments: [],
  team: [
    {
      id: "u1",
      name: "Ahmed Abdelgawad",
      initials: "AA",
      role: "Admin",
      branch: "Egypt",
      email: "ahmed@trygc.com",
      active: true,
    },
    {
      id: "u2",
      name: "Sara Al-Otaibi",
      initials: "SO",
      role: "Sales",
      branch: "Saudi Arabia",
      email: "sara@trygc.com",
      active: true,
    },
    {
      id: "u3",
      name: "Omar Hassan",
      initials: "OH",
      role: "Sales",
      branch: "Egypt",
      email: "omar@trygc.com",
      active: true,
    },
    {
      id: "u4",
      name: "Layla Mansour",
      initials: "LM",
      role: "Sales",
      branch: "UAE",
      email: "layla@trygc.com",
      active: true,
    },
    {
      id: "u5",
      name: "Yousef Al-Sabah",
      initials: "YS",
      role: "Sales",
      branch: "Kuwait",
      email: "yousef@trygc.com",
      active: true,
    },
    {
      id: "u6",
      name: "Nour El-Din",
      initials: "NE",
      role: "Management",
      branch: "Egypt",
      email: "nour@trygc.com",
      active: true,
    },
    {
      id: "u7",
      name: "Huda Al-Qahtani",
      initials: "HQ",
      role: "Management",
      branch: "Saudi Arabia",
      email: "huda@trygc.com",
      active: true,
    },
    {
      id: "u8",
      name: "Karim Fathy",
      initials: "KF",
      role: "Finance",
      branch: "Egypt",
      email: "karim@trygc.com",
      active: true,
    },
    {
      id: "u9",
      name: "Mariam Saleh",
      initials: "MS",
      role: "Finance",
      branch: "UAE",
      email: "mariam@trygc.com",
      active: true,
    },
  ],
  rules: {
    currentUserId: "u1",
    activeScope: "Group",
    baseCurrency: "SAR",
    requireManagementApproval: true,
    requireFinanceApproval: true,
    autoInvoiceOnClientApproval: true,
    enforceRoleAccess: true,
    followUpDays: 3,
    quotationValidityDays: 14,
  },
  fxToSar: { SAR: 1, EGP: 0.078, AED: 1.02, KWD: 12.2, QAR: 1.03, BHD: 9.95 },
  activationCampaigns: [
    {
      id: "CPN-3001",
      name: "Riyadh Seasonal Launch",
      companyId: "CMP-1000",
      branch: "Saudi Arabia",
      city: "Riyadh",
      campaignOwner: "Sara Al-Otaibi",
      operationsOwner: "Omar Hassan",
      backupOwner: "Layla Mansour",
      target: 24,
      startDate: day(-4),
      endDate: day(25),
      postingRequirement: "One verified reel and two story frames",
      brief: "Creator activation with scheduled visits and verified posting coverage.",
      budget: 180000,
      currency: "SAR",
      health: "Amber",
      status: "Active",
      rootCause: "Confirmation gap",
      impact: "Six creators remain below target",
      nextAction: "Confirm replacement shortlist",
      eta: day(3),
    },
    {
      id: "CPN-3002",
      name: "Cairo Campus Tour",
      companyId: "CMP-1003",
      branch: "Egypt",
      city: "Cairo",
      campaignOwner: "Omar Hassan",
      operationsOwner: "Omar Hassan",
      backupOwner: "Sara Al-Otaibi",
      target: 18,
      startDate: day(-9),
      endDate: day(18),
      postingRequirement: "One campus reel and a carousel recap",
      brief: "Student-led coverage across three universities with verified attendance.",
      budget: 420000,
      currency: "EGP",
      health: "Green",
      status: "Active",
      rootCause: "On track",
      impact: "Delivery ahead of the posting schedule",
      nextAction: "Verify the outstanding coverage links",
      eta: day(2),
    },
    {
      id: "CPN-3003",
      name: "Dubai Wearables Launch",
      companyId: "CMP-1002",
      branch: "UAE",
      city: "Dubai",
      campaignOwner: "Layla Mansour",
      operationsOwner: "Layla Mansour",
      backupOwner: "Yousef Al-Sabah",
      target: 14,
      startDate: day(-16),
      endDate: day(9),
      postingRequirement: "Unboxing reel plus a seven-day usage story",
      brief: "Tech-first creators covering the wearables launch wave.",
      budget: 96000,
      currency: "AED",
      health: "Red",
      status: "Active",
      rootCause: "Coverage quality below the agreed standard",
      impact: "Client report blocked pending QA review",
      nextAction: "Complete the QA pass and reissue the brief",
      eta: day(1),
    },
    {
      id: "CPN-3004",
      name: "Kuwait Studio Relaunch",
      companyId: "CMP-1004",
      branch: "Kuwait",
      city: "Kuwait City",
      campaignOwner: "Yousef Al-Sabah",
      operationsOwner: "Yousef Al-Sabah",
      backupOwner: "Layla Mansour",
      target: 11,
      startDate: day(6),
      endDate: day(34),
      postingRequirement: "Class attendance reel and a member testimonial",
      brief: "Fitness creators covering the relaunched studio floor.",
      budget: 7200,
      currency: "KWD",
      health: "Green",
      status: "Planning",
      rootCause: "Not started",
      impact: "Shortlist pending client sign-off",
      nextAction: "Share the creator shortlist for approval",
      eta: day(4),
    },
  ],
  influencers: demoInfluencers,
  operationsQueue: demoOperationsQueue,
  entities: [
    { id: "ENT-SA", name: "Grand Community Saudi Arabia", country: "Saudi Arabia", currency: "SAR", status: "Active" },
    { id: "ENT-AE", name: "Grand Community UAE", country: "UAE", currency: "AED", status: "Active" },
    { id: "ENT-KW", name: "Grand Community Kuwait", country: "Kuwait", currency: "KWD", status: "Active" },
    { id: "ENT-EG", name: "Grand Community Egypt", country: "Egypt", currency: "EGP", status: "Active" },
    { id: "ENT-QA", name: "Grand Community Qatar", country: "Qatar", currency: "QAR", status: "Setup" },
    { id: "ENT-BH", name: "Grand Community Bahrain", country: "Bahrain", currency: "BHD", status: "Setup" },
  ],
  chartOfAccounts: [
    {
      code: "1100",
      name: "Cash and Bank",
      type: "Asset",
      groupCategory: "Current Assets",
      entityApplicability: ["Saudi Arabia", "UAE", "Kuwait", "Egypt", "Qatar", "Bahrain"],
      active: true,
      approvedBy: "Finance & Administration Manager",
      effectiveDate: "2026-01-01",
    },
    {
      code: "1200",
      name: "Accounts Receivable",
      type: "Asset",
      groupCategory: "Current Assets",
      entityApplicability: ["Saudi Arabia", "UAE", "Kuwait", "Egypt", "Qatar", "Bahrain"],
      active: true,
      approvedBy: "Finance & Administration Manager",
      effectiveDate: "2026-01-01",
    },
    {
      code: "2100",
      name: "Accounts Payable",
      type: "Liability",
      groupCategory: "Current Liabilities",
      entityApplicability: ["Saudi Arabia", "UAE", "Kuwait", "Egypt", "Qatar", "Bahrain"],
      active: true,
      approvedBy: "Finance & Administration Manager",
      effectiveDate: "2026-01-01",
    },
    {
      code: "4100",
      name: "Campaign Revenue",
      type: "Revenue",
      groupCategory: "Operating Revenue",
      entityApplicability: ["Saudi Arabia", "UAE", "Kuwait", "Egypt", "Qatar", "Bahrain"],
      active: true,
      approvedBy: "Finance & Administration Manager",
      effectiveDate: "2026-01-01",
    },
    {
      code: "5100",
      name: "Creator Costs",
      type: "Expense",
      groupCategory: "Cost of Revenue",
      entityApplicability: ["Saudi Arabia", "UAE", "Kuwait", "Egypt", "Qatar", "Bahrain"],
      active: true,
      approvedBy: "Finance & Administration Manager",
      effectiveDate: "2026-01-01",
    },
  ],
  accountRequests: [],
  financeInvoices: demoInvoices,
  auditLog: [
    {
      id: "AUD-1",
      user: "Omar Hassan",
      action: "Received posting coverage",
      module: "Campaigns",
      record: "INF-4002",
      entity: "Saudi Arabia",
      timestamp: "2026-09-04T11:45:00Z",
      oldValue: "Visited",
      newValue: "Posting Coverage Received",
    },
  ],
};
