import type {
  Activity,
  Brand,
  Campaign,
  CampaignInfluencer,
  Company,
  CreatorLedgerEntry,
  FinanceExpense,
  FinanceInvoice,
  InfluencerStage,
  Lead,
  OperationsWorkItem,
} from "./types";

/**
 * Demo records are anchored to the current date so approval SLAs, overdue tasks,
 * and the four-week cash view stay meaningful instead of drifting into the past.
 */
const DAY = 86_400_000;
export const day = (offset: number) => new Date(Date.now() + offset * DAY).toISOString().slice(0, 10);
export const stamp = (hoursAgo: number) => new Date(Date.now() - hoursAgo * 3_600_000).toISOString();

const event = (id: string, title: string, detail: string, daysAgo: number) => ({
  id,
  title,
  detail,
  createdAt: stamp(daysAgo * 24),
});

export const demoCompanies: Company[] = [
  {
    id: "CMP-1000",
    name: "Aurora Retail",
    contactPerson: "Nada El-Sayed",
    phone: "+966 58 571 7613",
    email: "nada@auroraretail.com",
    website: "www.auroraretail.com",
    industry: "F&B",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    status: "Active",
    createdAt: day(-206),
    requestedInfluencers: 131,
    freeInfluencers: 12,
    usedInfluencers: 86,
    source: "Grand OS starter",
  },
  {
    id: "CMP-1001",
    name: "Bayan Retail",
    contactPerson: "Faisal Al-Harbi",
    phone: "+966 55 210 4488",
    email: "faisal@bayanretail.sa",
    website: "www.bayanretail.sa",
    industry: "Retail",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    status: "Active",
    createdAt: day(-181),
    requestedInfluencers: 64,
    freeInfluencers: 6,
    usedInfluencers: 41,
    source: "Grand OS starter",
  },
  {
    id: "CMP-1002",
    name: "Orbit Labs",
    contactPerson: "Reem Al-Marzouqi",
    phone: "+971 50 448 9021",
    email: "reem@orbitlabs.ae",
    website: "www.orbitlabs.ae",
    industry: "Technology",
    owner: "Layla Mansour",
    branch: "UAE",
    status: "Active",
    createdAt: day(-175),
    requestedInfluencers: 48,
    freeInfluencers: 4,
    usedInfluencers: 22,
    source: "Grand OS starter",
  },
  {
    id: "CMP-1003",
    name: "Nile Foods Group",
    contactPerson: "Mostafa Zaki",
    phone: "+20 100 774 2210",
    email: "mostafa@nilefoods.eg",
    website: "www.nilefoods.eg",
    industry: "F&B",
    owner: "Omar Hassan",
    branch: "Egypt",
    status: "Active",
    createdAt: day(-160),
    requestedInfluencers: 96,
    freeInfluencers: 9,
    usedInfluencers: 58,
    source: "Workspace",
  },
  {
    id: "CMP-1004",
    name: "Gulf Wellness Co",
    contactPerson: "Dalal Al-Rashed",
    phone: "+965 6600 3312",
    email: "dalal@gulfwellness.kw",
    website: "www.gulfwellness.kw",
    industry: "Health & Fitness",
    owner: "Yousef Al-Sabah",
    branch: "Kuwait",
    status: "Active",
    createdAt: day(-142),
    requestedInfluencers: 36,
    freeInfluencers: 3,
    usedInfluencers: 19,
    source: "Workspace",
  },
  {
    id: "CMP-1005",
    name: "Cedar Beauty",
    contactPerson: "Lama Al-Ghamdi",
    phone: "+966 56 903 7745",
    email: "lama@cedarbeauty.sa",
    website: "www.cedarbeauty.sa",
    industry: "Beauty",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    status: "Active",
    createdAt: day(-118),
    requestedInfluencers: 72,
    freeInfluencers: 8,
    usedInfluencers: 34,
    source: "Workspace",
  },
  {
    id: "CMP-1006",
    name: "Dune Automotive",
    contactPerson: "Khalid Bin Sultan",
    phone: "+971 55 662 1180",
    email: "khalid@duneauto.ae",
    website: "www.duneauto.ae",
    industry: "Automotive",
    owner: "Layla Mansour",
    branch: "UAE",
    status: "Prospect",
    createdAt: day(-64),
    requestedInfluencers: 20,
    freeInfluencers: 0,
    usedInfluencers: 0,
    source: "Workspace",
  },
  {
    id: "CMP-1007",
    name: "Cairo Tech Labs",
    contactPerson: "Salma Ibrahim",
    phone: "+20 122 908 5533",
    email: "salma@cairotech.eg",
    website: "www.cairotech.eg",
    industry: "Technology",
    owner: "Omar Hassan",
    branch: "Egypt",
    status: "Active",
    createdAt: day(-97),
    requestedInfluencers: 54,
    freeInfluencers: 5,
    usedInfluencers: 27,
    source: "Workspace",
  },
  {
    id: "CMP-1008",
    name: "Marina Hospitality",
    contactPerson: "Bader Al-Enezi",
    phone: "+965 9977 4410",
    email: "bader@marinahospitality.kw",
    website: "www.marinahospitality.kw",
    industry: "Hospitality",
    owner: "Yousef Al-Sabah",
    branch: "Kuwait",
    status: "Prospect",
    createdAt: day(-41),
    requestedInfluencers: 18,
    freeInfluencers: 2,
    usedInfluencers: 0,
    source: "Workspace",
  },
  {
    id: "CMP-1009",
    name: "Rawaa Fashion",
    contactPerson: "Hessa Al-Dossari",
    phone: "+966 53 118 2094",
    email: "hessa@rawaa.sa",
    website: "www.rawaa.sa",
    industry: "Fashion",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    status: "Inactive",
    createdAt: day(-233),
    requestedInfluencers: 40,
    freeInfluencers: 4,
    usedInfluencers: 40,
    source: "Grand OS starter",
  },
];

export const demoBrands: Brand[] = [
  {
    id: "BRD-2000",
    name: "Aurora Coffee",
    companyId: "CMP-1000",
    contactPerson: "Nada El-Sayed",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    industry: "F&B",
    status: "Active",
    requestedInfluencers: 74,
    freeInfluencers: 8,
    usedInfluencers: 52,
  },
  {
    id: "BRD-2001",
    name: "Aurora Bakehouse",
    companyId: "CMP-1000",
    contactPerson: "Nada El-Sayed",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    industry: "F&B",
    status: "Active",
    requestedInfluencers: 57,
    freeInfluencers: 4,
    usedInfluencers: 34,
  },
  {
    id: "BRD-2002",
    name: "Bayan Home",
    companyId: "CMP-1001",
    contactPerson: "Faisal Al-Harbi",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    industry: "Retail",
    status: "Active",
    requestedInfluencers: 38,
    freeInfluencers: 4,
    usedInfluencers: 26,
  },
  {
    id: "BRD-2003",
    name: "Bayan Kids",
    companyId: "CMP-1001",
    contactPerson: "Faisal Al-Harbi",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    industry: "Retail",
    status: "Active",
    requestedInfluencers: 26,
    freeInfluencers: 2,
    usedInfluencers: 15,
  },
  {
    id: "BRD-2004",
    name: "Orbit Wearables",
    companyId: "CMP-1002",
    contactPerson: "Reem Al-Marzouqi",
    owner: "Layla Mansour",
    branch: "UAE",
    industry: "Technology",
    status: "Active",
    requestedInfluencers: 30,
    freeInfluencers: 3,
    usedInfluencers: 14,
  },
  {
    id: "BRD-2005",
    name: "Orbit Home Audio",
    companyId: "CMP-1002",
    contactPerson: "Reem Al-Marzouqi",
    owner: "Layla Mansour",
    branch: "UAE",
    industry: "Technology",
    status: "Active",
    requestedInfluencers: 18,
    freeInfluencers: 1,
    usedInfluencers: 8,
  },
  {
    id: "BRD-2006",
    name: "Nile Dairy",
    companyId: "CMP-1003",
    contactPerson: "Mostafa Zaki",
    owner: "Omar Hassan",
    branch: "Egypt",
    industry: "F&B",
    status: "Active",
    requestedInfluencers: 58,
    freeInfluencers: 6,
    usedInfluencers: 38,
  },
  {
    id: "BRD-2007",
    name: "Nile Snacks",
    companyId: "CMP-1003",
    contactPerson: "Mostafa Zaki",
    owner: "Omar Hassan",
    branch: "Egypt",
    industry: "F&B",
    status: "Active",
    requestedInfluencers: 38,
    freeInfluencers: 3,
    usedInfluencers: 20,
  },
  {
    id: "BRD-2008",
    name: "Gulf Wellness Studios",
    companyId: "CMP-1004",
    contactPerson: "Dalal Al-Rashed",
    owner: "Yousef Al-Sabah",
    branch: "Kuwait",
    industry: "Health & Fitness",
    status: "Active",
    requestedInfluencers: 36,
    freeInfluencers: 3,
    usedInfluencers: 19,
  },
  {
    id: "BRD-2009",
    name: "Cedar Skincare",
    companyId: "CMP-1005",
    contactPerson: "Lama Al-Ghamdi",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    industry: "Beauty",
    status: "Active",
    requestedInfluencers: 44,
    freeInfluencers: 5,
    usedInfluencers: 22,
  },
  {
    id: "BRD-2010",
    name: "Cedar Fragrance",
    companyId: "CMP-1005",
    contactPerson: "Lama Al-Ghamdi",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    industry: "Beauty",
    status: "Prospect",
    requestedInfluencers: 28,
    freeInfluencers: 3,
    usedInfluencers: 12,
  },
  {
    id: "BRD-2011",
    name: "Cairo Tech Cloud",
    companyId: "CMP-1007",
    contactPerson: "Salma Ibrahim",
    owner: "Omar Hassan",
    branch: "Egypt",
    industry: "Technology",
    status: "Active",
    requestedInfluencers: 54,
    freeInfluencers: 5,
    usedInfluencers: 27,
  },
];

export const demoLeads: Lead[] = [
  {
    id: "LED-4000",
    leadName: "Zahra Organics launch",
    companyName: "Zahra Organics",
    firstName: "Maha",
    lastName: "Al-Zahrani",
    phone: "+966 54 771 2280",
    email: "maha@zahraorganics.sa",
    branch: "Saudi Arabia",
    owner: "Sara Al-Otaibi",
    source: "Instagram",
    status: "Qualified",
    createdAt: day(-34),
    lastActivityAt: day(-3),
    nextActivityAt: day(2),
    notes: "Wants 20 creators for a Riyadh store opening in the next quarter.",
    qualifiedAt: day(-19),
    budgetConfirmed: true,
    meetingHeld: true,
    expectedCreators: 20,
    opportunityValue: 240000,
  },
  {
    id: "LED-4001",
    leadName: "Delta Mobility awareness",
    companyName: "Delta Mobility",
    firstName: "Tarek",
    lastName: "Shawky",
    phone: "+20 111 220 4471",
    email: "tarek@deltamobility.eg",
    branch: "Egypt",
    owner: "Omar Hassan",
    source: "LinkedIn",
    status: "Working",
    createdAt: day(-27),
    lastActivityAt: day(-6),
    nextActivityAt: day(1),
    notes: "Budget approval sits with the group CFO; second meeting requested.",
    meetingHeld: true,
    expectedCreators: 14,
    opportunityValue: 310000,
  },
  {
    id: "LED-4002",
    leadName: "Vega Fitness club opening",
    companyName: "Vega Fitness",
    firstName: "Hind",
    lastName: "Al-Mutairi",
    phone: "+965 9944 1120",
    email: "hind@vegafitness.kw",
    branch: "Kuwait",
    owner: "Yousef Al-Sabah",
    source: "Referral",
    status: "Qualified",
    createdAt: day(-48),
    lastActivityAt: day(-2),
    nextActivityAt: day(4),
    notes: "Referred by Gulf Wellness. Two branches, staggered launch.",
    qualifiedAt: day(-25),
    budgetConfirmed: true,
    meetingHeld: true,
    expectedCreators: 12,
    opportunityValue: 9800,
  },
  {
    id: "LED-4003",
    leadName: "Helio Electronics teaser",
    companyName: "Helio Electronics",
    firstName: "Ziad",
    lastName: "Nassar",
    phone: "+971 52 330 8891",
    email: "ziad@helio.ae",
    branch: "UAE",
    owner: "Layla Mansour",
    source: "Event",
    status: "Contacted",
    createdAt: day(-16),
    lastActivityAt: day(-9),
    nextActivityAt: null,
    notes: "Met at GITEX. Needs a category proposal before committing.",
    expectedCreators: 8,
    opportunityValue: 46000,
  },
  {
    id: "LED-4004",
    leadName: "Sahara Travel seasonal",
    companyName: "Sahara Travel",
    firstName: "Rana",
    lastName: "Abdulaziz",
    phone: "+966 50 664 3319",
    email: "rana@saharatravel.sa",
    branch: "Saudi Arabia",
    owner: "Sara Al-Otaibi",
    source: "Website",
    status: "New",
    createdAt: day(-5),
    lastActivityAt: null,
    nextActivityAt: day(1),
    notes: "Inbound form submission, no contact attempt recorded yet.",
    expectedCreators: 10,
    opportunityValue: 120000,
  },
  {
    id: "LED-4005",
    leadName: "Levant Furniture rollout",
    companyName: "Levant Furniture",
    firstName: "Wael",
    lastName: "Haddad",
    phone: "+20 128 553 9902",
    email: "wael@levantfurniture.eg",
    branch: "Egypt",
    owner: "Omar Hassan",
    source: "Partner",
    status: "Converted",
    createdAt: day(-121),
    lastActivityAt: day(-88),
    nextActivityAt: null,
    convertedCompanyId: "CMP-1007",
    notes: "Converted into Cairo Tech Labs group account.",
    qualifiedAt: day(-110),
    convertedAt: day(-97),
    budgetConfirmed: true,
    meetingHeld: true,
    expectedCreators: 30,
    opportunityValue: 640000,
  },
  {
    id: "LED-4006",
    leadName: "Pearl Jewellery gifting",
    companyName: "Pearl Jewellery",
    firstName: "Amal",
    lastName: "Al-Kandari",
    phone: "+965 6611 7724",
    email: "amal@pearljewellery.kw",
    branch: "Kuwait",
    owner: "Yousef Al-Sabah",
    source: "Instagram",
    status: "Working",
    createdAt: day(-39),
    lastActivityAt: day(-21),
    nextActivityAt: day(-2),
    notes: "Gifting campaign for the festive season; awaiting creator list.",
    meetingHeld: true,
    expectedCreators: 9,
    opportunityValue: 6400,
  },
  {
    id: "LED-4007",
    leadName: "Nova Clinics awareness",
    companyName: "Nova Clinics",
    firstName: "Sami",
    lastName: "Al-Dosari",
    phone: "+966 55 442 1187",
    email: "sami@novaclinics.sa",
    branch: "Saudi Arabia",
    owner: "Sara Al-Otaibi",
    source: "Cold Call",
    status: "Junk",
    createdAt: day(-72),
    lastActivityAt: day(-70),
    nextActivityAt: null,
    notes: "Not a decision maker; no budget authority in this financial year.",
    expectedCreators: 0,
    opportunityValue: 0,
  },
  {
    id: "LED-4008",
    leadName: "Atlas Logistics B2B",
    companyName: "Atlas Logistics",
    firstName: "Nader",
    lastName: "Fouad",
    phone: "+971 56 118 2043",
    email: "nader@atlaslogistics.ae",
    branch: "UAE",
    owner: "Layla Mansour",
    source: "LinkedIn",
    status: "Qualified",
    createdAt: day(-53),
    lastActivityAt: day(-4),
    nextActivityAt: day(3),
    notes: "B2B thought-leadership angle; wants LinkedIn-first creators.",
    qualifiedAt: day(-30),
    budgetConfirmed: false,
    meetingHeld: true,
    expectedCreators: 6,
    opportunityValue: 52000,
  },
  {
    id: "LED-4009",
    leadName: "Karam Grocers relaunch",
    companyName: "Karam Grocers",
    firstName: "Iman",
    lastName: "Serag",
    phone: "+20 106 771 3390",
    email: "iman@karamgrocers.eg",
    branch: "Egypt",
    owner: "Omar Hassan",
    source: "Referral",
    status: "Converted",
    createdAt: day(-168),
    lastActivityAt: day(-155),
    nextActivityAt: null,
    convertedCompanyId: "CMP-1003",
    notes: "Converted into Nile Foods Group.",
    qualifiedAt: day(-166),
    convertedAt: day(-160),
    budgetConfirmed: true,
    meetingHeld: true,
    expectedCreators: 24,
    opportunityValue: 520000,
  },
  {
    id: "LED-4010",
    leadName: "Mira Cosmetics sampling",
    companyName: "Mira Cosmetics",
    firstName: "Dana",
    lastName: "Al-Shammari",
    phone: "+966 53 902 4471",
    email: "dana@miracosmetics.sa",
    branch: "Saudi Arabia",
    owner: "Sara Al-Otaibi",
    source: "Event",
    status: "Contacted",
    createdAt: day(-11),
    lastActivityAt: day(-11),
    nextActivityAt: null,
    notes: "No follow-up logged since first contact.",
    expectedCreators: 15,
    opportunityValue: 175000,
  },
  {
    id: "LED-4011",
    leadName: "Bahri Seafood launch",
    companyName: "Bahri Seafood",
    firstName: "Talal",
    lastName: "Al-Otaibi",
    phone: "+965 9922 5518",
    email: "talal@bahriseafood.kw",
    branch: "Kuwait",
    owner: "Yousef Al-Sabah",
    source: "Website",
    status: "New",
    createdAt: day(-2),
    lastActivityAt: null,
    nextActivityAt: day(2),
    notes: "Inbound enquiry for a restaurant opening.",
    expectedCreators: 7,
    opportunityValue: 5200,
  },
  {
    id: "LED-4012",
    leadName: "Verde Interiors showcase",
    companyName: "Verde Interiors",
    firstName: "Yara",
    lastName: "Mansour",
    phone: "+971 50 990 1123",
    email: "yara@verdeinteriors.ae",
    branch: "UAE",
    owner: "Layla Mansour",
    source: "Partner",
    status: "Working",
    createdAt: day(-22),
    lastActivityAt: day(-7),
    nextActivityAt: day(5),
    notes: "Design-led creators only; brand is protective of tone.",
    meetingHeld: true,
    expectedCreators: 11,
    opportunityValue: 68000,
  },
  {
    id: "LED-4013",
    leadName: "Anwar Education enrolment",
    companyName: "Anwar Education",
    firstName: "Hatem",
    lastName: "Rashwan",
    phone: "+20 109 442 8871",
    email: "hatem@anwaredu.eg",
    branch: "Egypt",
    owner: "Omar Hassan",
    source: "Cold Call",
    status: "Working",
    createdAt: day(-30),
    lastActivityAt: day(-18),
    nextActivityAt: day(-4),
    notes: "Enrolment season campaign; follow-up date already passed.",
    meetingHeld: false,
    expectedCreators: 18,
    opportunityValue: 290000,
  },
];

type QuotationSeed = {
  id: string;
  name: string;
  companyId: string;
  brandId: string | null;
  owner: string;
  branch: Campaign["branch"];
  currency: Campaign["currency"];
  quantity: number;
  unitPrice: number;
  freeCreators: number;
  discount: number;
  serviceFee: number;
  vatPercent: number;
  credit: number;
  costRatio: number;
  stage: Campaign["stage"];
  approvalStatus: Campaign["approvalStatus"];
  createdDaysAgo: number;
  updatedHoursAgo: number;
  closeInDays: number;
  pdfReady: boolean;
  invoiceId: string | null;
  lossReason?: Campaign["lossReason"];
  lossNotes?: string;
};

const quotationSeeds: QuotationSeed[] = [
  {
    id: "QT-5000",
    name: "Aurora Coffee autumn tasting",
    companyId: "CMP-1000",
    brandId: "BRD-2000",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    currency: "SAR",
    quantity: 18,
    unitPrice: 6800,
    freeCreators: 2,
    discount: 4000,
    serviceFee: 6000,
    vatPercent: 15,
    credit: 0,
    costRatio: 0.62,
    stage: "Client Approved",
    approvalStatus: "Approved",
    createdDaysAgo: 74,
    updatedHoursAgo: 720,
    closeInDays: -38,
    pdfReady: true,
    invoiceId: "INV-9000",
  },
  {
    id: "QT-5001",
    name: "Aurora Bakehouse store openings",
    companyId: "CMP-1000",
    brandId: "BRD-2001",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    currency: "SAR",
    quantity: 12,
    unitPrice: 7200,
    freeCreators: 1,
    discount: 0,
    serviceFee: 4500,
    vatPercent: 15,
    credit: 0,
    costRatio: 0.6,
    stage: "Financial Review",
    approvalStatus: "Pending Finance",
    createdDaysAgo: 9,
    updatedHoursAgo: 58,
    closeInDays: 12,
    pdfReady: false,
    invoiceId: null,
  },
  {
    id: "QT-5002",
    name: "Bayan Home living refresh",
    companyId: "CMP-1001",
    brandId: "BRD-2002",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    currency: "SAR",
    quantity: 15,
    unitPrice: 5600,
    freeCreators: 2,
    discount: 3000,
    serviceFee: 3500,
    vatPercent: 15,
    credit: 0,
    costRatio: 0.58,
    stage: "Client Approved",
    approvalStatus: "Approved",
    createdDaysAgo: 52,
    updatedHoursAgo: 528,
    closeInDays: -21,
    pdfReady: true,
    invoiceId: "INV-9001",
  },
  {
    id: "QT-5003",
    name: "Bayan Kids back to school",
    companyId: "CMP-1001",
    brandId: "BRD-2003",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    currency: "SAR",
    quantity: 10,
    unitPrice: 4900,
    freeCreators: 1,
    discount: 1500,
    serviceFee: 2500,
    vatPercent: 15,
    credit: 0,
    costRatio: 0.64,
    stage: "Sent To Client",
    approvalStatus: "Approved",
    createdDaysAgo: 17,
    updatedHoursAgo: 196,
    closeInDays: 6,
    pdfReady: true,
    invoiceId: null,
  },
  {
    id: "QT-5004",
    name: "Orbit Wearables launch wave",
    companyId: "CMP-1002",
    brandId: "BRD-2004",
    owner: "Layla Mansour",
    branch: "UAE",
    currency: "AED",
    quantity: 14,
    unitPrice: 1850,
    freeCreators: 2,
    discount: 1200,
    serviceFee: 900,
    vatPercent: 5,
    credit: 0,
    costRatio: 0.59,
    stage: "Client Approved",
    approvalStatus: "Approved",
    createdDaysAgo: 61,
    updatedHoursAgo: 600,
    closeInDays: -29,
    pdfReady: true,
    invoiceId: "INV-9002",
  },
  {
    id: "QT-5005",
    name: "Orbit Home Audio review series",
    companyId: "CMP-1002",
    brandId: "BRD-2005",
    owner: "Layla Mansour",
    branch: "UAE",
    currency: "AED",
    quantity: 8,
    unitPrice: 2100,
    freeCreators: 1,
    discount: 0,
    serviceFee: 600,
    vatPercent: 5,
    credit: 0,
    costRatio: 0.57,
    stage: "Management Review",
    approvalStatus: "Pending Management",
    createdDaysAgo: 4,
    updatedHoursAgo: 79,
    closeInDays: 18,
    pdfReady: false,
    invoiceId: null,
  },
  {
    id: "QT-5006",
    name: "Nile Dairy ramadan build-up",
    companyId: "CMP-1003",
    brandId: "BRD-2006",
    owner: "Omar Hassan",
    branch: "Egypt",
    currency: "EGP",
    quantity: 22,
    unitPrice: 22000,
    freeCreators: 3,
    discount: 18000,
    serviceFee: 24000,
    vatPercent: 14,
    credit: 0,
    costRatio: 0.61,
    stage: "Client Approved",
    approvalStatus: "Approved",
    createdDaysAgo: 88,
    updatedHoursAgo: 840,
    closeInDays: -47,
    pdfReady: true,
    invoiceId: "INV-9003",
  },
  {
    id: "QT-5007",
    name: "Nile Snacks campus tour",
    companyId: "CMP-1003",
    brandId: "BRD-2007",
    owner: "Omar Hassan",
    branch: "Egypt",
    currency: "EGP",
    quantity: 16,
    unitPrice: 19500,
    freeCreators: 2,
    discount: 9000,
    serviceFee: 15000,
    vatPercent: 14,
    credit: 0,
    costRatio: 0.63,
    stage: "Released",
    approvalStatus: "Approved",
    createdDaysAgo: 12,
    updatedHoursAgo: 41,
    closeInDays: 9,
    pdfReady: true,
    invoiceId: null,
  },
  {
    id: "QT-5008",
    name: "Gulf Wellness member drive",
    companyId: "CMP-1004",
    brandId: "BRD-2008",
    owner: "Yousef Al-Sabah",
    branch: "Kuwait",
    currency: "KWD",
    quantity: 11,
    unitPrice: 620,
    freeCreators: 1,
    discount: 300,
    serviceFee: 250,
    vatPercent: 0,
    credit: 0,
    costRatio: 0.6,
    stage: "Client Approved",
    approvalStatus: "Approved",
    createdDaysAgo: 44,
    updatedHoursAgo: 432,
    closeInDays: -17,
    pdfReady: true,
    invoiceId: "INV-9004",
  },
  {
    id: "QT-5009",
    name: "Gulf Wellness studio relaunch",
    companyId: "CMP-1004",
    brandId: "BRD-2008",
    owner: "Yousef Al-Sabah",
    branch: "Kuwait",
    currency: "KWD",
    quantity: 9,
    unitPrice: 680,
    freeCreators: 1,
    discount: 0,
    serviceFee: 180,
    vatPercent: 0,
    credit: 0,
    costRatio: 0.58,
    stage: "Proposal / Price Quote",
    approvalStatus: "Not Submitted",
    createdDaysAgo: 3,
    updatedHoursAgo: 20,
    closeInDays: 24,
    pdfReady: false,
    invoiceId: null,
  },
  {
    id: "QT-5010",
    name: "Cedar Skincare hero product",
    companyId: "CMP-1005",
    brandId: "BRD-2009",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    currency: "SAR",
    quantity: 20,
    unitPrice: 6200,
    freeCreators: 2,
    discount: 5000,
    serviceFee: 7000,
    vatPercent: 15,
    credit: 0,
    costRatio: 0.6,
    stage: "Client Approved",
    approvalStatus: "Approved",
    createdDaysAgo: 35,
    updatedHoursAgo: 336,
    closeInDays: -12,
    pdfReady: true,
    invoiceId: "INV-9005",
  },
  {
    id: "QT-5011",
    name: "Cedar Fragrance gifting edit",
    companyId: "CMP-1005",
    brandId: "BRD-2010",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    currency: "SAR",
    quantity: 13,
    unitPrice: 5800,
    freeCreators: 1,
    discount: 2000,
    serviceFee: 4000,
    vatPercent: 15,
    credit: 0,
    costRatio: 0.62,
    stage: "Management Review",
    approvalStatus: "Pending Management",
    createdDaysAgo: 6,
    updatedHoursAgo: 30,
    closeInDays: 15,
    pdfReady: false,
    invoiceId: null,
  },
  {
    id: "QT-5012",
    name: "Cairo Tech Cloud developer series",
    companyId: "CMP-1007",
    brandId: "BRD-2011",
    owner: "Omar Hassan",
    branch: "Egypt",
    currency: "EGP",
    quantity: 12,
    unitPrice: 26000,
    freeCreators: 1,
    discount: 12000,
    serviceFee: 18000,
    vatPercent: 14,
    credit: 0,
    costRatio: 0.59,
    stage: "Client Approved",
    approvalStatus: "Approved",
    createdDaysAgo: 66,
    updatedHoursAgo: 648,
    closeInDays: -33,
    pdfReady: true,
    invoiceId: "INV-9006",
  },
  {
    id: "QT-5013",
    name: "Cairo Tech Cloud enterprise push",
    companyId: "CMP-1007",
    brandId: "BRD-2011",
    owner: "Omar Hassan",
    branch: "Egypt",
    currency: "EGP",
    quantity: 9,
    unitPrice: 28000,
    freeCreators: 0,
    discount: 0,
    serviceFee: 12000,
    vatPercent: 14,
    credit: 0,
    costRatio: 0.6,
    stage: "Financial Review",
    approvalStatus: "Pending Finance",
    createdDaysAgo: 7,
    updatedHoursAgo: 92,
    closeInDays: 11,
    pdfReady: false,
    invoiceId: null,
  },
  {
    id: "QT-5014",
    name: "Marina Hospitality soft launch",
    companyId: "CMP-1008",
    brandId: null,
    owner: "Yousef Al-Sabah",
    branch: "Kuwait",
    currency: "KWD",
    quantity: 7,
    unitPrice: 720,
    freeCreators: 1,
    discount: 0,
    serviceFee: 150,
    vatPercent: 0,
    credit: 0,
    costRatio: 0.61,
    stage: "Sent To Client",
    approvalStatus: "Approved",
    createdDaysAgo: 21,
    updatedHoursAgo: 240,
    closeInDays: 4,
    pdfReady: true,
    invoiceId: null,
  },
  {
    id: "QT-5015",
    name: "Dune Automotive test-drive week",
    companyId: "CMP-1006",
    brandId: null,
    owner: "Layla Mansour",
    branch: "UAE",
    currency: "AED",
    quantity: 10,
    unitPrice: 2400,
    freeCreators: 0,
    discount: 0,
    serviceFee: 1200,
    vatPercent: 5,
    credit: 0,
    costRatio: 0.63,
    stage: "Proposal / Price Quote",
    approvalStatus: "Not Submitted",
    createdDaysAgo: 2,
    updatedHoursAgo: 14,
    closeInDays: 27,
    pdfReady: false,
    invoiceId: null,
  },
  {
    id: "QT-5016",
    name: "Rawaa Fashion capsule drop",
    companyId: "CMP-1009",
    brandId: null,
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    currency: "SAR",
    quantity: 16,
    unitPrice: 5200,
    freeCreators: 2,
    discount: 0,
    serviceFee: 4000,
    vatPercent: 15,
    credit: 0,
    costRatio: 0.66,
    stage: "Client Not Approved",
    approvalStatus: "Approved",
    createdDaysAgo: 96,
    updatedHoursAgo: 1440,
    closeInDays: -60,
    pdfReady: true,
    invoiceId: null,
    lossReason: "Price",
    lossNotes: "Client compared against a lower agency fee and paused the category.",
  },
  {
    id: "QT-5017",
    name: "Aurora Coffee winter menu",
    companyId: "CMP-1000",
    brandId: "BRD-2000",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    currency: "SAR",
    quantity: 11,
    unitPrice: 6400,
    freeCreators: 1,
    discount: 0,
    serviceFee: 3000,
    vatPercent: 15,
    credit: 0,
    costRatio: 0.6,
    stage: "Client Not Approved",
    approvalStatus: "Approved",
    createdDaysAgo: 58,
    updatedHoursAgo: 1080,
    closeInDays: -30,
    pdfReady: true,
    invoiceId: null,
    lossReason: "Timing",
    lossNotes: "Deferred to the next financial year after a marketing freeze.",
  },
  {
    id: "QT-5018",
    name: "Nile Snacks influencer bundle",
    companyId: "CMP-1003",
    brandId: "BRD-2007",
    owner: "Omar Hassan",
    branch: "Egypt",
    currency: "EGP",
    quantity: 14,
    unitPrice: 21000,
    freeCreators: 2,
    discount: 6000,
    serviceFee: 11000,
    vatPercent: 14,
    credit: 0,
    costRatio: 0.64,
    stage: "Client Cancelled",
    approvalStatus: "Approved",
    createdDaysAgo: 77,
    updatedHoursAgo: 1200,
    closeInDays: -44,
    pdfReady: true,
    invoiceId: null,
    lossReason: "Campaign cancelled",
    lossNotes: "Product recall paused all above-the-line activity.",
  },
  {
    id: "QT-5019",
    name: "Orbit Wearables retention push",
    companyId: "CMP-1002",
    brandId: "BRD-2004",
    owner: "Layla Mansour",
    branch: "UAE",
    currency: "AED",
    quantity: 6,
    unitPrice: 1950,
    freeCreators: 0,
    discount: 0,
    serviceFee: 450,
    vatPercent: 5,
    credit: 0,
    costRatio: 0.58,
    stage: "Released",
    approvalStatus: "Approved",
    createdDaysAgo: 10,
    updatedHoursAgo: 34,
    closeInDays: 8,
    pdfReady: true,
    invoiceId: null,
  },
  {
    id: "QT-5020",
    name: "Cedar Skincare pharmacy tie-in",
    companyId: "CMP-1005",
    brandId: "BRD-2009",
    owner: "Sara Al-Otaibi",
    branch: "Saudi Arabia",
    currency: "SAR",
    quantity: 8,
    unitPrice: 6000,
    freeCreators: 1,
    discount: 0,
    serviceFee: 2200,
    vatPercent: 15,
    credit: 0,
    costRatio: 0.61,
    stage: "Client Approved",
    approvalStatus: "Approved",
    createdDaysAgo: 26,
    updatedHoursAgo: 264,
    closeInDays: -6,
    pdfReady: true,
    invoiceId: "INV-9007",
  },
  {
    id: "QT-5021",
    name: "Nile Dairy school programme",
    companyId: "CMP-1003",
    brandId: "BRD-2006",
    owner: "Omar Hassan",
    branch: "Egypt",
    currency: "EGP",
    quantity: 18,
    unitPrice: 20500,
    freeCreators: 2,
    discount: 8000,
    serviceFee: 14000,
    vatPercent: 14,
    credit: 0,
    costRatio: 0.62,
    stage: "Management Review",
    approvalStatus: "Revision Required",
    createdDaysAgo: 14,
    updatedHoursAgo: 122,
    closeInDays: 10,
    pdfReady: false,
    invoiceId: null,
  },
];

const stageEvents: Record<Campaign["stage"], string[]> = {
  "Proposal / Price Quote": ["Quotation created"],
  "Management Review": ["Quotation created", "Submitted for management approval"],
  "Financial Review": ["Quotation created", "Management approved", "Submitted for finance approval"],
  Released: ["Quotation created", "Management approved", "Finance approved", "Released for delivery"],
  "Sent To Client": ["Quotation created", "Management approved", "Finance approved", "Released", "Sent to client"],
  "Client Approved": [
    "Quotation created",
    "Management approved",
    "Finance approved",
    "Released",
    "Sent to client",
    "Client approved",
  ],
  "Client Not Approved": [
    "Quotation created",
    "Management approved",
    "Finance approved",
    "Sent to client",
    "Client declined",
  ],
  "Client Cancelled": [
    "Quotation created",
    "Management approved",
    "Finance approved",
    "Sent to client",
    "Client cancelled",
  ],
};

export const demoQuotations: Campaign[] = quotationSeeds.map((seed) => {
  const base = seed.quantity * seed.unitPrice;
  const subtotal = base - seed.discount + seed.serviceFee;
  const tax = Math.round((subtotal * seed.vatPercent) / 100);
  const budget = subtotal + tax - seed.credit;
  const cost = Math.round(base * seed.costRatio);
  const timeline = stageEvents[seed.stage];
  return {
    id: seed.id,
    name: seed.name,
    companyId: seed.companyId,
    brandId: seed.brandId,
    owner: seed.owner,
    branch: seed.branch,
    currency: seed.currency,
    budget,
    requestedInfluencers: seed.quantity,
    stage: seed.stage,
    approvalStatus: seed.approvalStatus,
    createdAt: day(-seed.createdDaysAgo),
    updatedAt: stamp(seed.updatedHoursAgo),
    followUpDue: seed.stage === "Sent To Client" ? day(2) : null,
    pdfReady: seed.pdfReady,
    invoiceId: seed.invoiceId,
    expectedCloseDate: day(seed.closeInDays),
    lossReason: seed.lossReason,
    lossNotes: seed.lossNotes,
    pricing: {
      unitPrice: seed.unitPrice,
      freeCreators: seed.freeCreators,
      discount: seed.discount,
      serviceFee: seed.serviceFee,
      vatPercent: seed.vatPercent,
      credit: seed.credit,
      influencerCost: Math.round(cost * 0.72),
      executionCost: Math.round(cost * 0.18),
      operationsCost: cost - Math.round(cost * 0.72) - Math.round(cost * 0.18),
    },
    fxSnapshot: {
      rate: { SAR: 1, EGP: 0.078, AED: 1.02, KWD: 12.2, QAR: 1.03, BHD: 9.95 }[seed.currency],
      effectiveAt: day(-seed.createdDaysAgo),
      source: "Treasury planning rate",
      actor: "Karim Fathy",
    },
    history: timeline.map((title, index) =>
      event(
        `${seed.id}-EVT-${index}`,
        title,
        `${title} for ${seed.name}.`,
        Math.max(0, seed.createdDaysAgo - index * Math.ceil(seed.createdDaysAgo / (timeline.length + 1))),
      ),
    ),
  };
});

export const demoInvoices: FinanceInvoice[] = [
  {
    id: "INV-9000",
    companyId: "CMP-1000",
    campaignId: null,
    quotationId: "QT-5000",
    entity: "Saudi Arabia",
    currency: "SAR",
    amount: 149500,
    paidAmount: 149500,
    status: "Paid",
    createdAt: day(-70),
    issuedAt: day(-69),
    sentAt: day(-69),
    dueDate: day(-39),
    paymentTerms: "Net 30",
    poNumber: "PO-AUR-4471",
    collectionsOwner: "Karim Fathy",
    subtotal: 130000,
    tax: 19500,
    payments: [
      { id: "PAY-1", amount: 74750, reference: "SNB-88213", recordedAt: day(-52), actor: "Karim Fathy" },
      { id: "PAY-2", amount: 74750, reference: "SNB-90114", recordedAt: day(-40), actor: "Karim Fathy" },
    ],
  },
  {
    id: "INV-9001",
    companyId: "CMP-1001",
    campaignId: null,
    quotationId: "QT-5002",
    entity: "Saudi Arabia",
    currency: "SAR",
    amount: 98325,
    paidAmount: 50000,
    status: "Partially Paid",
    createdAt: day(-48),
    issuedAt: day(-47),
    sentAt: day(-47),
    dueDate: day(-17),
    paymentTerms: "Net 30",
    poNumber: "PO-BYN-2210",
    collectionsOwner: "Karim Fathy",
    subtotal: 85500,
    tax: 12825,
    payments: [{ id: "PAY-3", amount: 50000, reference: "RJH-44120", recordedAt: day(-24), actor: "Karim Fathy" }],
  },
  {
    id: "INV-9002",
    companyId: "CMP-1002",
    campaignId: null,
    quotationId: "QT-5004",
    entity: "UAE",
    currency: "AED",
    amount: 27142,
    paidAmount: 0,
    status: "Sent",
    createdAt: day(-57),
    issuedAt: day(-56),
    sentAt: day(-56),
    dueDate: day(-11),
    paymentTerms: "Net 45",
    poNumber: "PO-ORB-1188",
    collectionsOwner: "Mariam Saleh",
    subtotal: 25850,
    tax: 1292,
    payments: [],
  },
  {
    id: "INV-9003",
    companyId: "CMP-1003",
    campaignId: null,
    quotationId: "QT-5006",
    entity: "Egypt",
    currency: "EGP",
    amount: 559500,
    paidAmount: 300000,
    status: "Partially Paid",
    createdAt: day(-84),
    issuedAt: day(-83),
    sentAt: day(-83),
    dueDate: day(9),
    paymentTerms: "Net 60",
    poNumber: "PO-NFG-7741",
    collectionsOwner: "Karim Fathy",
    subtotal: 490000,
    tax: 68600,
    creditAmount: 12000,
    payments: [{ id: "PAY-4", amount: 300000, reference: "CIB-77219", recordedAt: day(-31), actor: "Karim Fathy" }],
    creditNotes: [
      {
        id: "CN-1",
        amount: 12000,
        reason: "Two creators replaced after a delivery delay",
        issuedAt: day(-28),
        actor: "Karim Fathy",
      },
    ],
  },
  {
    id: "INV-9004",
    companyId: "CMP-1004",
    campaignId: null,
    quotationId: "QT-5008",
    entity: "Kuwait",
    currency: "KWD",
    amount: 6770,
    paidAmount: 6770,
    status: "Paid",
    createdAt: day(-40),
    issuedAt: day(-39),
    sentAt: day(-39),
    dueDate: day(-9),
    paymentTerms: "Net 30",
    poNumber: "PO-GWC-9930",
    collectionsOwner: "Mariam Saleh",
    subtotal: 6770,
    tax: 0,
    payments: [{ id: "PAY-5", amount: 6770, reference: "NBK-33017", recordedAt: day(-12), actor: "Mariam Saleh" }],
  },
  {
    id: "INV-9005",
    companyId: "CMP-1005",
    campaignId: null,
    quotationId: "QT-5010",
    entity: "Saudi Arabia",
    currency: "SAR",
    amount: 145820,
    paidAmount: 0,
    status: "Sent",
    createdAt: day(-31),
    issuedAt: day(-30),
    sentAt: day(-30),
    dueDate: day(5),
    paymentTerms: "Net 35",
    poNumber: "PO-CDR-5514",
    collectionsOwner: "Karim Fathy",
    subtotal: 126800,
    tax: 19020,
    payments: [],
  },
  {
    id: "INV-9006",
    companyId: "CMP-1007",
    campaignId: null,
    quotationId: "QT-5012",
    entity: "Egypt",
    currency: "EGP",
    amount: 362520,
    paidAmount: 362520,
    status: "Paid",
    createdAt: day(-62),
    issuedAt: day(-61),
    sentAt: day(-61),
    dueDate: day(-31),
    paymentTerms: "Net 30",
    poNumber: "PO-CTL-8820",
    collectionsOwner: "Karim Fathy",
    subtotal: 318000,
    tax: 44520,
    payments: [{ id: "PAY-6", amount: 362520, reference: "NBE-12094", recordedAt: day(-33), actor: "Karim Fathy" }],
  },
  {
    id: "INV-9007",
    companyId: "CMP-1005",
    campaignId: null,
    quotationId: "QT-5020",
    entity: "Saudi Arabia",
    currency: "SAR",
    amount: 57730,
    paidAmount: 0,
    status: "Issued",
    createdAt: day(-8),
    issuedAt: day(-7),
    dueDate: day(22),
    paymentTerms: "Net 30",
    poNumber: "PO-CDR-6611",
    collectionsOwner: "Karim Fathy",
    subtotal: 50200,
    tax: 7530,
    payments: [],
  },
  {
    id: "INV-9008",
    companyId: "CMP-1000",
    campaignId: null,
    entity: "Saudi Arabia",
    currency: "SAR",
    amount: 42000,
    paidAmount: 0,
    status: "Pending Approval",
    createdAt: day(-3),
    dueDate: day(27),
    paymentTerms: "Net 30",
    poNumber: "",
    collectionsOwner: "Karim Fathy",
    subtotal: 36522,
    tax: 5478,
    payments: [],
  },
  {
    id: "INV-9009",
    companyId: "CMP-1002",
    campaignId: null,
    entity: "UAE",
    currency: "AED",
    amount: 18375,
    paidAmount: 0,
    status: "Draft",
    createdAt: day(-1),
    dueDate: day(34),
    paymentTerms: "Net 45",
    poNumber: "",
    collectionsOwner: "Mariam Saleh",
    subtotal: 17500,
    tax: 875,
    payments: [],
  },
  {
    id: "INV-9010",
    companyId: "CMP-1003",
    campaignId: null,
    entity: "Egypt",
    currency: "EGP",
    amount: 208000,
    paidAmount: 0,
    status: "Sent",
    createdAt: day(-96),
    issuedAt: day(-95),
    sentAt: day(-95),
    dueDate: day(-46),
    paymentTerms: "Net 45",
    poNumber: "PO-NFG-4402",
    collectionsOwner: "Karim Fathy",
    subtotal: 182456,
    tax: 25544,
    payments: [],
  },
];

export const demoExpenses: FinanceExpense[] = [
  {
    id: "EXP-7000",
    quotationId: "QT-5000",
    companyId: "CMP-1000",
    supplier: "Creator payouts batch 24-08",
    category: "Influencer",
    amount: 68000,
    currency: "SAR",
    dueDate: day(-34),
    paid: true,
    reference: "EXP-REF-4200",
    recordedAt: day(-40),
    actor: "Karim Fathy",
  },
  {
    id: "EXP-7001",
    quotationId: "QT-5000",
    companyId: "CMP-1000",
    supplier: "Riyadh production crew",
    category: "Execution",
    amount: 18500,
    currency: "SAR",
    dueDate: day(-30),
    paid: true,
    reference: "EXP-REF-4201",
    recordedAt: day(-38),
    actor: "Karim Fathy",
  },
  {
    id: "EXP-7002",
    quotationId: "QT-5002",
    companyId: "CMP-1001",
    supplier: "Creator payouts batch 24-09",
    category: "Influencer",
    amount: 41000,
    currency: "SAR",
    dueDate: day(4),
    paid: false,
    reference: "EXP-REF-4202",
    recordedAt: day(-14),
    actor: "Karim Fathy",
  },
  {
    id: "EXP-7003",
    quotationId: "QT-5004",
    companyId: "CMP-1002",
    supplier: "Dubai creator collective",
    category: "Influencer",
    amount: 12400,
    currency: "AED",
    dueDate: day(11),
    paid: false,
    reference: "EXP-REF-4203",
    recordedAt: day(-20),
    actor: "Mariam Saleh",
  },
  {
    id: "EXP-7004",
    quotationId: "QT-5004",
    companyId: "CMP-1002",
    supplier: "Logistics and gifting",
    category: "Operations",
    amount: 3100,
    currency: "AED",
    dueDate: day(-4),
    paid: false,
    reference: "EXP-REF-4204",
    recordedAt: day(-25),
    actor: "Mariam Saleh",
  },
  {
    id: "EXP-7005",
    quotationId: "QT-5006",
    companyId: "CMP-1003",
    supplier: "Cairo creator network",
    category: "Influencer",
    amount: 264000,
    currency: "EGP",
    dueDate: day(-12),
    paid: true,
    reference: "EXP-REF-4205",
    recordedAt: day(-60),
    actor: "Karim Fathy",
  },
  {
    id: "EXP-7006",
    quotationId: "QT-5006",
    companyId: "CMP-1003",
    supplier: "Studio hire and edit",
    category: "Execution",
    amount: 58000,
    currency: "EGP",
    dueDate: day(6),
    paid: false,
    reference: "EXP-REF-4206",
    recordedAt: day(-30),
    actor: "Karim Fathy",
  },
  {
    id: "EXP-7007",
    quotationId: "QT-5008",
    companyId: "CMP-1004",
    supplier: "Kuwait creator roster",
    category: "Influencer",
    amount: 3900,
    currency: "KWD",
    dueDate: day(2),
    paid: false,
    reference: "EXP-REF-4207",
    recordedAt: day(-18),
    actor: "Mariam Saleh",
  },
  {
    id: "EXP-7008",
    quotationId: "QT-5010",
    companyId: "CMP-1005",
    supplier: "Beauty creator panel",
    category: "Influencer",
    amount: 62000,
    currency: "SAR",
    dueDate: day(9),
    paid: false,
    reference: "EXP-REF-4208",
    recordedAt: day(-16),
    actor: "Karim Fathy",
  },
  {
    id: "EXP-7009",
    quotationId: "QT-5010",
    companyId: "CMP-1005",
    supplier: "Sampling fulfilment",
    category: "Operations",
    amount: 8800,
    currency: "SAR",
    dueDate: day(17),
    paid: false,
    reference: "EXP-REF-4209",
    recordedAt: day(-10),
    actor: "Karim Fathy",
  },
  {
    id: "EXP-7010",
    quotationId: "QT-5012",
    companyId: "CMP-1007",
    supplier: "Developer advocate panel",
    category: "Influencer",
    amount: 178000,
    currency: "EGP",
    dueDate: day(-20),
    paid: true,
    reference: "EXP-REF-4210",
    recordedAt: day(-50),
    actor: "Karim Fathy",
  },
  {
    id: "EXP-7011",
    quotationId: "QT-5012",
    companyId: "CMP-1007",
    supplier: "Event streaming partner",
    category: "Execution",
    amount: 44000,
    currency: "EGP",
    dueDate: day(20),
    paid: false,
    reference: "EXP-REF-4211",
    recordedAt: day(-22),
    actor: "Karim Fathy",
  },
  {
    id: "EXP-7012",
    quotationId: "QT-5020",
    companyId: "CMP-1005",
    supplier: "Pharmacy creator tie-in",
    category: "Influencer",
    amount: 29000,
    currency: "SAR",
    dueDate: day(14),
    paid: false,
    reference: "EXP-REF-4212",
    recordedAt: day(-9),
    actor: "Karim Fathy",
  },
  {
    id: "EXP-7013",
    quotationId: "QT-5007",
    companyId: "CMP-1003",
    supplier: "Campus activation staffing",
    category: "Operations",
    amount: 36000,
    currency: "EGP",
    dueDate: day(25),
    paid: false,
    reference: "EXP-REF-4213",
    recordedAt: day(-6),
    actor: "Karim Fathy",
  },
];

const ledgerSeeds: {
  companyId: string;
  brandId: string | null;
  quotationId?: string;
  kind: CreatorLedgerEntry["kind"];
  quantity: number;
  note: string;
  actor: string;
  daysAgo: number;
}[] = [
  {
    companyId: "CMP-1000",
    brandId: "BRD-2000",
    kind: "Purchased",
    quantity: 74,
    note: "Annual entitlement for Aurora Coffee",
    actor: "Karim Fathy",
    daysAgo: 200,
  },
  {
    companyId: "CMP-1000",
    brandId: "BRD-2000",
    kind: "Bonus",
    quantity: 8,
    note: "Renewal bonus creators",
    actor: "Huda Al-Qahtani",
    daysAgo: 200,
  },
  {
    companyId: "CMP-1000",
    brandId: "BRD-2000",
    quotationId: "QT-5000",
    kind: "Consumed",
    quantity: 52,
    note: "Delivered on the autumn tasting activation",
    actor: "Sara Al-Otaibi",
    daysAgo: 40,
  },
  {
    companyId: "CMP-1000",
    brandId: "BRD-2001",
    kind: "Purchased",
    quantity: 57,
    note: "Bakehouse store opening entitlement",
    actor: "Karim Fathy",
    daysAgo: 180,
  },
  {
    companyId: "CMP-1000",
    brandId: "BRD-2001",
    quotationId: "QT-5001",
    kind: "Reserved",
    quantity: 12,
    note: "Held while the quotation sits with finance",
    actor: "Sara Al-Otaibi",
    daysAgo: 9,
  },
  {
    companyId: "CMP-1000",
    brandId: "BRD-2001",
    kind: "Consumed",
    quantity: 34,
    note: "Delivered across three store openings",
    actor: "Sara Al-Otaibi",
    daysAgo: 60,
  },
  {
    companyId: "CMP-1001",
    brandId: "BRD-2002",
    kind: "Purchased",
    quantity: 38,
    note: "Bayan Home entitlement",
    actor: "Karim Fathy",
    daysAgo: 175,
  },
  {
    companyId: "CMP-1001",
    brandId: "BRD-2002",
    quotationId: "QT-5002",
    kind: "Consumed",
    quantity: 26,
    note: "Living refresh delivery",
    actor: "Sara Al-Otaibi",
    daysAgo: 25,
  },
  {
    companyId: "CMP-1001",
    brandId: "BRD-2003",
    kind: "Purchased",
    quantity: 26,
    note: "Bayan Kids entitlement",
    actor: "Karim Fathy",
    daysAgo: 170,
  },
  {
    companyId: "CMP-1001",
    brandId: "BRD-2003",
    quotationId: "QT-5003",
    kind: "Reserved",
    quantity: 10,
    note: "Held while the quotation sits with the client",
    actor: "Sara Al-Otaibi",
    daysAgo: 17,
  },
  {
    companyId: "CMP-1002",
    brandId: "BRD-2004",
    kind: "Purchased",
    quantity: 30,
    note: "Orbit Wearables entitlement",
    actor: "Mariam Saleh",
    daysAgo: 170,
  },
  {
    companyId: "CMP-1002",
    brandId: "BRD-2004",
    quotationId: "QT-5004",
    kind: "Consumed",
    quantity: 14,
    note: "Launch wave delivery",
    actor: "Layla Mansour",
    daysAgo: 30,
  },
  {
    companyId: "CMP-1002",
    brandId: "BRD-2005",
    kind: "Purchased",
    quantity: 18,
    note: "Home Audio entitlement",
    actor: "Mariam Saleh",
    daysAgo: 160,
  },
  {
    companyId: "CMP-1002",
    brandId: "BRD-2005",
    kind: "Consumed",
    quantity: 8,
    note: "Review series delivery",
    actor: "Layla Mansour",
    daysAgo: 45,
  },
  {
    companyId: "CMP-1003",
    brandId: "BRD-2006",
    kind: "Purchased",
    quantity: 58,
    note: "Nile Dairy entitlement",
    actor: "Karim Fathy",
    daysAgo: 155,
  },
  {
    companyId: "CMP-1003",
    brandId: "BRD-2006",
    kind: "Bonus",
    quantity: 6,
    note: "Volume bonus on renewal",
    actor: "Nour El-Din",
    daysAgo: 155,
  },
  {
    companyId: "CMP-1003",
    brandId: "BRD-2006",
    quotationId: "QT-5006",
    kind: "Consumed",
    quantity: 38,
    note: "Ramadan build-up delivery",
    actor: "Omar Hassan",
    daysAgo: 50,
  },
  {
    companyId: "CMP-1003",
    brandId: "BRD-2007",
    kind: "Purchased",
    quantity: 38,
    note: "Nile Snacks entitlement",
    actor: "Karim Fathy",
    daysAgo: 150,
  },
  {
    companyId: "CMP-1003",
    brandId: "BRD-2007",
    kind: "Consumed",
    quantity: 20,
    note: "Campus tour delivery",
    actor: "Omar Hassan",
    daysAgo: 35,
  },
  {
    companyId: "CMP-1003",
    brandId: "BRD-2007",
    kind: "Expired",
    quantity: 6,
    note: "Unused allocation lapsed at the end of the entitlement window",
    actor: "Karim Fathy",
    daysAgo: 12,
  },
  {
    companyId: "CMP-1004",
    brandId: "BRD-2008",
    kind: "Purchased",
    quantity: 36,
    note: "Gulf Wellness entitlement",
    actor: "Mariam Saleh",
    daysAgo: 140,
  },
  {
    companyId: "CMP-1004",
    brandId: "BRD-2008",
    quotationId: "QT-5008",
    kind: "Consumed",
    quantity: 19,
    note: "Member drive delivery",
    actor: "Yousef Al-Sabah",
    daysAgo: 20,
  },
  {
    companyId: "CMP-1005",
    brandId: "BRD-2009",
    kind: "Purchased",
    quantity: 44,
    note: "Cedar Skincare entitlement",
    actor: "Karim Fathy",
    daysAgo: 115,
  },
  {
    companyId: "CMP-1005",
    brandId: "BRD-2009",
    kind: "Bonus",
    quantity: 5,
    note: "Launch bonus creators",
    actor: "Huda Al-Qahtani",
    daysAgo: 115,
  },
  {
    companyId: "CMP-1005",
    brandId: "BRD-2009",
    quotationId: "QT-5010",
    kind: "Consumed",
    quantity: 22,
    note: "Hero product delivery",
    actor: "Sara Al-Otaibi",
    daysAgo: 14,
  },
  {
    companyId: "CMP-1005",
    brandId: "BRD-2010",
    kind: "Purchased",
    quantity: 28,
    note: "Cedar Fragrance entitlement",
    actor: "Karim Fathy",
    daysAgo: 100,
  },
  {
    companyId: "CMP-1005",
    brandId: "BRD-2010",
    kind: "Consumed",
    quantity: 12,
    note: "Gifting edit pilot",
    actor: "Sara Al-Otaibi",
    daysAgo: 40,
  },
  {
    companyId: "CMP-1007",
    brandId: "BRD-2011",
    kind: "Purchased",
    quantity: 54,
    note: "Cairo Tech Cloud entitlement",
    actor: "Karim Fathy",
    daysAgo: 95,
  },
  {
    companyId: "CMP-1007",
    brandId: "BRD-2011",
    quotationId: "QT-5012",
    kind: "Consumed",
    quantity: 27,
    note: "Developer series delivery",
    actor: "Omar Hassan",
    daysAgo: 34,
  },
  {
    companyId: "CMP-1007",
    brandId: "BRD-2011",
    kind: "Adjusted",
    quantity: 4,
    note: "Goodwill creators added after a scheduling error",
    actor: "Nour El-Din",
    daysAgo: 18,
  },
  {
    companyId: "CMP-1009",
    brandId: null,
    kind: "Purchased",
    quantity: 40,
    note: "Rawaa Fashion entitlement",
    actor: "Karim Fathy",
    daysAgo: 230,
  },
  {
    companyId: "CMP-1009",
    brandId: null,
    kind: "Consumed",
    quantity: 40,
    note: "Fully consumed before the account went inactive",
    actor: "Sara Al-Otaibi",
    daysAgo: 120,
  },
];

export const demoCreatorLedger: CreatorLedgerEntry[] = ledgerSeeds.map((seed, index) => ({
  id: `LGR-${8000 + index}`,
  companyId: seed.companyId,
  brandId: seed.brandId,
  quotationId: seed.quotationId,
  kind: seed.kind,
  quantity: seed.quantity,
  note: seed.note,
  actor: seed.actor,
  createdAt: day(-seed.daysAgo),
}));

const activitySeeds: {
  companyId: string;
  type: Activity["type"];
  title: string;
  status: Activity["status"];
  owner: string;
  daysAgo: number;
  dueInDays?: number;
  priority?: Activity["priority"];
  quotationId?: string;
  leadId?: string;
  brandId?: string;
  withOutcome?: boolean;
  outcome?: string;
}[] = [
  {
    companyId: "CMP-1000",
    type: "Meeting",
    title: "Autumn tasting kickoff with Aurora marketing",
    status: "Completed",
    owner: "Sara Al-Otaibi",
    daysAgo: 72,
    quotationId: "QT-5000",
    withOutcome: true,
  },
  {
    companyId: "CMP-1000",
    type: "Meeting",
    title: "Winter menu review",
    status: "Completed",
    owner: "Sara Al-Otaibi",
    daysAgo: 5,
    quotationId: "QT-5017",
  },
  {
    companyId: "CMP-1000",
    type: "Call",
    title: "Procurement paperwork chase",
    status: "Completed",
    owner: "Sara Al-Otaibi",
    daysAgo: 4,
    outcome: "Procurement confirmed the PO will be issued this week.",
  },
  {
    companyId: "CMP-1000",
    type: "Task",
    title: "Send updated creator shortlist",
    status: "Open",
    owner: "Sara Al-Otaibi",
    daysAgo: 9,
    dueInDays: -3,
    priority: "High",
    quotationId: "QT-5001",
  },
  {
    companyId: "CMP-1000",
    type: "Note",
    title: "Budget confirmed internally, waiting on procurement paperwork.",
    status: "Open",
    owner: "Sara Al-Otaibi",
    daysAgo: 7,
  },
  {
    companyId: "CMP-1001",
    type: "Meeting",
    title: "Bayan Home quarterly review",
    status: "Completed",
    owner: "Sara Al-Otaibi",
    daysAgo: 3,
  },
  {
    companyId: "CMP-1001",
    type: "Task",
    title: "Chase remaining balance on INV-9001",
    status: "Open",
    owner: "Karim Fathy",
    daysAgo: 12,
    dueInDays: -5,
    priority: "High",
  },
  {
    companyId: "CMP-1001",
    type: "Call",
    title: "Back to school timing check",
    status: "Completed",
    owner: "Sara Al-Otaibi",
    daysAgo: 6,
    quotationId: "QT-5003",
    outcome: "Client wants delivery to start the week after approval.",
  },
  {
    companyId: "CMP-1001",
    type: "Task",
    title: "Follow up on the back to school quotation",
    status: "Open",
    owner: "Sara Al-Otaibi",
    daysAgo: 2,
    dueInDays: 2,
    priority: "Medium",
    quotationId: "QT-5003",
  },
  {
    companyId: "CMP-1002",
    type: "Meeting",
    title: "Orbit launch wave retrospective",
    status: "Completed",
    owner: "Layla Mansour",
    daysAgo: 26,
    quotationId: "QT-5004",
    withOutcome: true,
  },
  {
    companyId: "CMP-1002",
    type: "Task",
    title: "Collect payment against INV-9002",
    status: "Open",
    owner: "Mariam Saleh",
    daysAgo: 11,
    dueInDays: -2,
    priority: "High",
  },
  {
    companyId: "CMP-1002",
    type: "Meeting",
    title: "Home audio review series planning",
    status: "Completed",
    owner: "Layla Mansour",
    daysAgo: 2,
    quotationId: "QT-5005",
  },
  {
    companyId: "CMP-1002",
    type: "Note",
    title: "Brand wants creators with a verified audio niche.",
    status: "Open",
    owner: "Layla Mansour",
    daysAgo: 2,
  },
  {
    companyId: "CMP-1003",
    type: "Meeting",
    title: "Nile Dairy delivery review",
    status: "Completed",
    owner: "Omar Hassan",
    daysAgo: 46,
    quotationId: "QT-5006",
    withOutcome: true,
  },
  {
    companyId: "CMP-1003",
    type: "Task",
    title: "Issue credit note for replaced creators",
    status: "Completed",
    owner: "Karim Fathy",
    daysAgo: 29,
    dueInDays: -28,
    priority: "Medium",
  },
  {
    companyId: "CMP-1003",
    type: "Task",
    title: "Escalate the overdue balance on INV-9010",
    status: "Open",
    owner: "Karim Fathy",
    daysAgo: 20,
    dueInDays: -8,
    priority: "High",
  },
  {
    companyId: "CMP-1003",
    type: "Call",
    title: "Campus tour scheduling",
    status: "Completed",
    owner: "Omar Hassan",
    daysAgo: 8,
    quotationId: "QT-5007",
    outcome: "Three campuses confirmed for the first delivery window.",
  },
  {
    companyId: "CMP-1003",
    type: "Meeting",
    title: "School programme scope discussion",
    status: "Completed",
    owner: "Omar Hassan",
    daysAgo: 1,
    quotationId: "QT-5021",
  },
  {
    companyId: "CMP-1004",
    type: "Meeting",
    title: "Gulf Wellness member drive wrap-up",
    status: "Completed",
    owner: "Yousef Al-Sabah",
    daysAgo: 18,
    quotationId: "QT-5008",
    withOutcome: true,
  },
  {
    companyId: "CMP-1004",
    type: "Task",
    title: "Prepare the studio relaunch pricing",
    status: "Open",
    owner: "Yousef Al-Sabah",
    daysAgo: 3,
    dueInDays: 1,
    priority: "Medium",
    quotationId: "QT-5009",
  },
  {
    companyId: "CMP-1005",
    type: "Meeting",
    title: "Cedar hero product launch review",
    status: "Completed",
    owner: "Sara Al-Otaibi",
    daysAgo: 12,
    quotationId: "QT-5010",
    withOutcome: true,
  },
  {
    companyId: "CMP-1005",
    type: "Task",
    title: "Send the fragrance gifting deck",
    status: "Open",
    owner: "Sara Al-Otaibi",
    daysAgo: 5,
    dueInDays: 3,
    priority: "Medium",
    quotationId: "QT-5011",
  },
  {
    companyId: "CMP-1005",
    type: "Call",
    title: "Pharmacy tie-in confirmation",
    status: "Completed",
    owner: "Sara Al-Otaibi",
    daysAgo: 7,
    quotationId: "QT-5020",
    outcome: "Pharmacy chain approved in-store sampling alongside the posts.",
  },
  {
    companyId: "CMP-1006",
    type: "Meeting",
    title: "Dune Automotive introduction",
    status: "Completed",
    owner: "Layla Mansour",
    daysAgo: 4,
  },
  {
    companyId: "CMP-1006",
    type: "Task",
    title: "Build the test-drive week proposal",
    status: "Open",
    owner: "Layla Mansour",
    daysAgo: 2,
    dueInDays: 4,
    priority: "High",
    quotationId: "QT-5015",
  },
  {
    companyId: "CMP-1007",
    type: "Meeting",
    title: "Developer series performance review",
    status: "Completed",
    owner: "Omar Hassan",
    daysAgo: 32,
    quotationId: "QT-5012",
    withOutcome: true,
  },
  {
    companyId: "CMP-1007",
    type: "Task",
    title: "Prepare enterprise push margin summary",
    status: "Open",
    owner: "Karim Fathy",
    daysAgo: 4,
    dueInDays: 1,
    priority: "High",
    quotationId: "QT-5013",
  },
  {
    companyId: "CMP-1007",
    type: "Call",
    title: "Enterprise stakeholder alignment",
    status: "Completed",
    owner: "Omar Hassan",
    daysAgo: 6,
    outcome: "CTO endorsed the plan; procurement review still pending.",
  },
  {
    companyId: "CMP-1008",
    type: "Meeting",
    title: "Marina soft launch walkthrough",
    status: "Completed",
    owner: "Yousef Al-Sabah",
    daysAgo: 9,
    quotationId: "QT-5014",
  },
  {
    companyId: "CMP-1008",
    type: "Task",
    title: "Chase the client decision on the soft launch",
    status: "Open",
    owner: "Yousef Al-Sabah",
    daysAgo: 6,
    dueInDays: -1,
    priority: "High",
    quotationId: "QT-5014",
  },
  {
    companyId: "CMP-1009",
    type: "Note",
    title: "Account paused after the capsule drop was declined on price.",
    status: "Open",
    owner: "Sara Al-Otaibi",
    daysAgo: 58,
  },
  {
    companyId: "CMP-1000",
    type: "Task",
    title: "Confirm creator replacements for the bakehouse wave",
    status: "Open",
    owner: "Omar Hassan",
    daysAgo: 1,
    dueInDays: 5,
    priority: "Low",
  },
];

export const demoActivities: Activity[] = activitySeeds.map((seed, index) => ({
  id: `ACT-${1000 + index}`,
  companyId: seed.companyId,
  type: seed.type,
  title: seed.title,
  status: seed.status,
  createdAt: day(-seed.daysAgo),
  owner: seed.owner,
  quotationId: seed.quotationId,
  leadId: seed.leadId,
  brandId: seed.brandId,
  dueDate: seed.dueInDays === undefined ? undefined : day(seed.dueInDays),
  priority: seed.priority,
  completedAt: seed.status === "Completed" ? day(-seed.daysAgo) : undefined,
  outcome: seed.outcome,
  meetingOutcome: seed.withOutcome
    ? {
        purpose: "Review delivery progress and agree the next commercial step",
        decision: "Proceed with the agreed creator mix",
        clientRequests: "Tighter posting schedule and weekly coverage reporting",
        budgetDiscussed: "Confirmed within the approved quotation value",
        expectedCreators: 12,
        nextAction: "Share the updated delivery plan",
        owner: seed.owner,
        deadline: day(3),
        nextMeeting: day(14),
      }
    : undefined,
}));

const influencerStages: InfluencerStage[] = [
  "Completed",
  "Posting Coverage Verified",
  "Visited",
  "Scheduled",
  "Approved",
  "Submitted to Client",
  "Confirmed",
  "Contacted",
  "Replacement Required",
  "Rejected",
];

const influencerNames = [
  "Reem Al-Harbi",
  "Yasmin Fouad",
  "Khalid Al-Amri",
  "Nour Sabry",
  "Hana Al-Rashid",
  "Tamer Adel",
  "Lina Al-Sayed",
  "Faris Al-Otaibi",
  "Mai Gamal",
  "Sultan Al-Dosari",
  "Rana Kamal",
  "Ziad Farouk",
  "Aisha Al-Nuaimi",
  "Mahmoud Refaat",
  "Shatha Al-Qahtani",
  "Karim Wahba",
  "Dana Al-Sabah",
  "Amr Halim",
  "Noura Al-Mutairi",
  "Basel Nassif",
  "Salma Adly",
  "Rakan Al-Shehri",
  "Farah Tawfik",
  "Majed Al-Enezi",
];

export const demoInfluencers: CampaignInfluencer[] = influencerNames.map((name, index) => {
  const campaignId = ["CPN-3001", "CPN-3002", "CPN-3003", "CPN-3004"][index % 4];
  const stage = influencerStages[index % influencerStages.length];
  const owner = ["Sara Al-Otaibi", "Omar Hassan", "Layla Mansour", "Yousef Al-Sabah"][index % 4];
  return {
    id: `INF-${6000 + index}`,
    campaignId,
    name,
    handle: `@${name.toLowerCase().replace(/[^a-z]+/g, "")}`,
    owner,
    stage,
    updatedAt: stamp((index % 9) * 24 + 6),
    history: [
      {
        id: `INF-${6000 + index}-H0`,
        stage,
        actor: owner,
        timestamp: stamp((index % 9) * 24 + 6),
        previousValue: "Prospected",
      },
    ],
  };
});

export const demoOperationsQueue: OperationsWorkItem[] = [
  {
    id: "OPS-8500",
    queue: "Onboarding",
    companyId: "CMP-1000",
    campaignId: "CPN-3001",
    influencerId: "INF-6007",
    owner: "Omar Hassan",
    priority: "High",
    status: "In Progress",
    createdAt: day(-4),
    deadline: day(1),
    slaHours: 48,
    nextAction: "Complete contracting for two confirmed creators",
    escalated: false,
  },
  {
    id: "OPS-8501",
    queue: "Coordination",
    companyId: "CMP-1000",
    campaignId: "CPN-3001",
    influencerId: "INF-6008",
    owner: "Sara Al-Otaibi",
    priority: "Critical",
    status: "Blocked",
    createdAt: day(-6),
    deadline: day(-1),
    slaHours: 24,
    nextAction: "Source a replacement after a late withdrawal",
    escalated: true,
  },
  {
    id: "OPS-8502",
    queue: "Visits",
    companyId: "CMP-1003",
    campaignId: "CPN-3002",
    influencerId: "INF-6002",
    owner: "Omar Hassan",
    priority: "Medium",
    status: "Open",
    createdAt: day(-2),
    deadline: day(3),
    slaHours: 72,
    nextAction: "Confirm store visit slots with the branch manager",
    escalated: false,
  },
  {
    id: "OPS-8503",
    queue: "Posting Coverage",
    companyId: "CMP-1003",
    campaignId: "CPN-3002",
    influencerId: "INF-6001",
    owner: "Omar Hassan",
    priority: "High",
    status: "In Progress",
    createdAt: day(-3),
    deadline: day(1),
    slaHours: 48,
    nextAction: "Collect and verify the outstanding reel links",
    escalated: false,
  },
  {
    id: "OPS-8504",
    queue: "WhatsApp",
    companyId: "CMP-1002",
    campaignId: "CPN-3003",
    influencerId: "INF-6006",
    owner: "Layla Mansour",
    priority: "Low",
    status: "Open",
    createdAt: day(-1),
    deadline: day(4),
    slaHours: 96,
    nextAction: "Send the briefing pack to the confirmed group",
    escalated: false,
  },
  {
    id: "OPS-8505",
    queue: "QA",
    companyId: "CMP-1002",
    campaignId: "CPN-3003",
    influencerId: null,
    owner: "Layla Mansour",
    priority: "Medium",
    status: "Open",
    createdAt: day(-5),
    deadline: day(-2),
    slaHours: 48,
    nextAction: "Review coverage quality before the client report",
    escalated: true,
  },
  {
    id: "OPS-8506",
    queue: "Coordination",
    companyId: "CMP-1004",
    campaignId: "CPN-3004",
    influencerId: "INF-6011",
    owner: "Yousef Al-Sabah",
    priority: "Medium",
    status: "In Progress",
    createdAt: day(-2),
    deadline: day(2),
    slaHours: 72,
    nextAction: "Lock the visit schedule for the studio relaunch",
    escalated: false,
  },
  {
    id: "OPS-8507",
    queue: "Onboarding",
    companyId: "CMP-1005",
    campaignId: "CPN-3001",
    influencerId: "INF-6015",
    owner: "Sara Al-Otaibi",
    priority: "Low",
    status: "Completed",
    createdAt: day(-9),
    deadline: day(-5),
    slaHours: 96,
    nextAction: "Onboarding complete",
    escalated: false,
  },
];
